trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - task: UseNode@1
    inputs:
      versionSpec: '10.x'
      checkLatest: true

  # - script: |
  #     git checkout main
  #     git config --global credential.helper store
  #     git config --global user.email "youremail@example.com"
  #     git config --global user.name "Your Name"
  #     git pull

    # displayName: 'Checkout and configure Git'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run build
    displayName: 'Build'

- job: BuildDockerImage
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      docker --version
    displayName: 'Check Docker Version'

  - script: |
      docker build -t veerabhadraswami/tictactoe:$(Build.BuildId) .
      echo "##vso[task.setvariable variable=DOCKER_IMAGE_TAG;isOutput=true]$(Build.BuildId)"
    displayName: 'Docker Build'

- job: PushDockerImage
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: BuildDockerImage
  steps:
  - script: |
      echo $(dockerhubPassword) | docker login -u $(dockerhubUser) --password-stdin
      docker push veerabhadraswami/tictactoe:$(DOCKER_IMAGE_TAG)
    displayName: 'Docker Push'

- job: Cleanup
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: [BuildDockerImage, PushDockerImage]
  steps:
  - script: |
      docker rmi veerabhadraswami/tictactoe:$(DOCKER_IMAGE_TAG)
    displayName: 'Docker Remove Local Image'
