apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tictactoe-app
  template:
    metadata:
      labels:
        app: tictactoe-app
    spec:
      containers:
        - name: tictactoe-app
          image: veerabhadraswami/tictactoe:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: tictactoe-service
# spec:
#   selector:
#     app: tictactoe-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3000
#   type: LoadBalancer
