pipeline {
  agent any
    
  tools {nodejs "nodejs"}
         // docker "docker"}
    
  stages {

    stage('Clear Workspace') {
            steps {
                // Delete the workspace
                deleteDir()
            }
        }
    stage('Cloning Git') {
      steps {
        script{
          git branch: 'main',
              credentialsId: 'github',
              url: 'https://github.com/veerabhadraswamy17/tictactoe-app.git'
        }
      }
    }
        
    stage('Install dependencies') {
      steps {
        script {
                    // Your Node.js build script
                    sh '''
                        # Increase the EventEmitter limit to suppress the warning
                        #node -e "require('events').EventEmitter.defaultMaxListeners = 20;"
                        #rm -rf node_modules package-lock.json
                        npm install
                        #npm start
                    '''
                }
      }
    }
     
    stage('Build') {
      steps {
         sh 'npm run build'
      }
    }
   // stage('Install Docker') {
   //          steps {
   //              script {
   //                  // Install Docker
   //                  sh '''
   //                      apt-get update
   //                      apt-get -y install apt-transport-https ca-certificates curl software-properties-common
   //                      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
   //                      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
   //                      apt-get update
   //                      apt-get -y install docker-ce
   //                  '''
   //              }
   //          }
   //      }

    stage('Docker Build') {
    	agent any
      steps {
      	sh 'docker build -t veerabhadraswami/tictactoe:latest .'
      }
    }

    
  }
}
