pipeline {
  agent any
    
  tools {nodejs "nodejs"
         dockerTool "docker"
        }

  environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
  }
    
  stages {

    stage('Clear Workspace') {
            steps {
                // Delete the workspace
                deleteDir()
            }
        }
    stage('Cloning Git') {
      steps {
        script{
          git branch: 'main',
              credentialsId: 'github',
              url: 'https://github.com/veerabhadraswamy17/tictactoe-app.git'
        }
      }
    }
        
    stage('Install dependencies') {
      steps {
        script {
                    // Your Node.js build script
                    sh '''
                        npm install
                    '''
                }
      }
    }
     
    stage('Build') {
      steps {
         sh 'npm run build'
      }
    }
   
    stage('Check Docker Version') {
    	agent any
      steps {
        sh 'docker --version'
      }
    }
    stage('Docker Build') {
    	agent any
      steps {
      	sh 'docker build -t veerabhadraswami/tictactoe:1.0 .'
      }
    }

    stage('DockerHub Login') {
      steps {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR'
      }
    }

    stage('Docker Push') {
      steps {
        sh 'docker push veerabhadraswami/tictactoe:1.0'
      }
    }
    // stage('Docker Build') {
    //   agent {
    //     docker {
    //       image 'docker' // Specify the Docker tool name defined in Jenkins
    //       args '-u root' // Run as root for Docker build (use with caution)
    //     }
    //   }
    //   steps {
    //     // sh 'docker build -t veerabhadraswami/tictactoe:latest .'
    //     sh 'docker --version'
    //   }
    // }
    
  }
    post {
    always {
      sh 'docker logout'
    }
  }
}
