pipeline {
  agent any
    
  tools {nodejs "nodejs"
         docker "docker"
        }
    
  stages {

    stage('Clear Workspace') {
            steps {
                // Delete the workspace
                deleteDir()
            }
        }
    stage('Cloning Git') {
      steps {
        script{
          git branch: 'main',
              credentialsId: 'github',
              url: 'https://github.com/veerabhadraswamy17/tictactoe-app.git'
        }
      }
    }
        
    stage('Install dependencies') {
      steps {
        script {
                    // Your Node.js build script
                    sh '''
                        npm install
                    '''
                }
      }
    }
     
    stage('Build') {
      steps {
         sh 'npm run build'
      }
    }
   
    // stage('Docker Build') {
    // 	agent any
    //   steps {
    //   	sh 'sudo docker build -t veerabhadraswami/tictactoe:latest .'
    //     //sh 'docker --version'
    //   }
    // }
    stage('Docker Build') {
      agent {
        docker {
          image 'docker' // Specify the Docker tool name defined in Jenkins
          args '-u root' // Run as root for Docker build (use with caution)
        }
      }
      steps {
        sh 'docker build -t veerabhadraswami/tictactoe:latest .'
      }
    }
    
  }
}
